import Foundation

nonisolated struct QSOADIFEncoder: Sendable {
    func encode(_ records: [QSOCachedRecord]) -> String {
        var output = "Generated by FMO Companion\n<ADIF_VER:5>3.1.4 <PROGRAMID:13>FMO Companion <EOH>\n"
        let dateFormatter = makeFormatter(format: "yyyyMMdd")
        let timeFormatter = makeFormatter(format: "HHmmss")
        for record in records.sorted(by: { $0.timestamp < $1.timestamp }) {
            var fields: [(String, String)] = []
            fields.append(("CALL", record.toCallsign))
            fields.append(("QSO_DATE", dateFormatter.string(from: record.timestamp)))
            fields.append(("TIME_ON", timeFormatter.string(from: record.timestamp)))
            if let mode = record.mode { fields.append(("MODE", mode.uppercased())) }
            if let frequencyRaw = record.frequencyRaw {
                fields.append(("FREQ", frequencyString(frequencyRaw)))
            }
            if let grid = record.toGrid { fields.append(("GRIDSQUARE", grid)) }
            if let ownGrid = record.fromGrid { fields.append(("MY_GRIDSQUARE", ownGrid)) }
            if let comment = record.comment { fields.append(("COMMENT", sanitized(comment))) }
            if let relayName = record.relayName { fields.append(("APP_FMO_RELAY", sanitized(relayName))) }
            if let relayAdmin = record.relayAdmin { fields.append(("APP_FMO_RELAY_ADMIN", sanitized(relayAdmin))) }
            fields.append(("APP_FMO_LOG_ID", String(record.logID)))
            output += fields.map(field).joined(separator: " ") + " <EOR>\n"
        }
        return output
    }

    private func makeFormatter(format: String) -> DateFormatter {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = .gmt
        formatter.dateFormat = format
        return formatter
    }

    private func field(_ pair: (String, String)) -> String {
        "<\(pair.0):\(pair.1.utf8.count)>\(pair.1)"
    }

    private func sanitized(_ value: String) -> String {
        value.replacingOccurrences(of: "<", with: "(").replacingOccurrences(of: ">", with: ")")
    }

    private func frequencyString(_ rawValue: Int64) -> String {
        let megahertz = Double(rawValue) / 10_000
        return megahertz.formatted(.number.locale(Locale(identifier: "en_US_POSIX")).precision(.fractionLength(4)))
    }
}
